services:

  postgres:
    image: postgres:16-alpine
    container_name: matricula_python_prod_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    volumes:
      - matricula_prod_data:/var/lib/postgresql/data
    networks:
      - dojo_python_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  profesor-service:
    image: ${DOCKERHUB_USERNAME}/profesor-service:latest
    container_name: profesor_service_prod
    environment:
      DATABASE_URL: postgresql://${DB_USER}:${DB_PASS}@postgres:5432/${DB_NAME}
    ports:
      - "8001:8001"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - dojo_python_network
    restart: unless-stopped

  matricula-service:
    image: ${DOCKERHUB_USERNAME}/matricula-service:latest
    container_name: matricula_service_prod
    environment:
      DATABASE_URL: postgresql://${DB_USER}:${DB_PASS}@postgres:5432/${DB_NAME}
      SECRET_KEY: ${DJANGO_SECRET_KEY}
      DEBUG: "False"
    ports:
      - "8002:8002"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - dojo_python_network
    restart: unless-stopped

networks:
  dojo_python_network:
    driver: bridge

volumes:
  matricula_prod_data: