sonar.projectKey=manusixx_dojo-python-matricula
sonar.organization=manusixx
sonar.host.url=https://sonarcloud.io

# Rutas de los reportes de cobertura de cada servicio
sonar.python.coverage.reportPaths=profesor-service/coverage.xml,matricula-service/coverage.xml

# Excluir archivos que no son código de negocio
sonar.exclusions=**/migrations/**,**/__pycache__/**,**/alembic/**,**/tests/**