# Generated by Django 5.1.4 on 2026-06-11 20:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("estudiantes", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Curso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("codigo", models.CharField(max_length=20, unique=True)),
                ("nombre", models.CharField(max_length=150)),
                (
                    "creditos",
                    models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
                ),
                ("profesor_id", models.IntegerField()),
                (
                    "estudiantes",
                    models.ManyToManyField(
                        blank=True, related_name="cursos", to="estudiantes.estudiante"
                    ),
                ),
            ],
            options={
                "db_table": "cursos",
                "ordering": ["codigo"],
            },
        ),
    ]
